services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/var/www
  frontend:
    build:
      context:  .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/src:/app
    command: sh -c "npm run dev"
    ports:
      - 3000:3000
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: illust_web_app
      MYSQL_ROOT_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - "3001:80"



volumes:
  mysql-volume: